### ISSUE TITLE
POA nomineelist 0x00000... account

### ISSUE THREAD

**Issue by arrivets** [mosaicnetworks/evm-lite#16]
When an account moves from nomineelist to whitelist, it leaves behind an entry for the 0 account.

`
evmlc$ poa nomineelist 
[{"address":"0x0000000000000000000000000000000000000000","moniker":"","upVotes":0,"downVotes":0}]
`

**Comment by jonknight73** [comment]
A solidity fix has been made in the monetd repository. 

https://github.com/mosaicnetworks/monetd/commit/44a4dbcf16c944e6e976d46ba9e19ddcdedc5529
