### ISSUE TITLE
make vendor failed

### ISSUE THREAD

**Issue by yenchihliao** [mosaicnetworks/evm-lite#22]
When using "make vendor" on ubuntu16.04, 
We encountered this error: 
"[ERROR] Error scanning github.com/allegro/bigcache/v2/queue: cannot find package "." in:
        /home/yenchih/.glide/cache/src/https-github.com-allegro-bigcache/v2/queue
[ERROR] Failed to retrieve a list of dependencies: Error resolving imports".

**Comment by jonknight73** [comment]
I have attempted to reproduce this error unsuccessfully. Potentially there has been a glitch in the glide process and there is a corrupted or incomplete repository in the glide cache.

Could you try the nuclear reset option please? I.e:

$ rm -rf vendor
$ glide cc
$ make vendor

The glide cc command clears the glide cache. 

If this does not resolve the issue, please let us know.

**Comment by arrivets** [comment]
They introduced a breaking change in that library.

The solution is to fix the version in the glide.yaml file:

```
   package: github.com/allegro/bigcache
    version: v2.0.0
    subpackages:
    - queue
`
I did fixed it in the develop branch. Will be merged in the next release

**Comment by yenchihliao** [comment]
@jonknight73 your solution didn't work. It's possible that glide won't try to install the package, which is not available now,  when you already have it. Hence you can't reproduce the error.

I solve my problem by following @arrivets 's advice. Replace my current glide.yaml by the one one develop branch.
